all:
	gcc filestruct.c -o base
	gcc insertsort.c -o insert
	#gcc insertlist.c -o insertlist
	g++ quicksort.c  -o quick

	#g++ insertlist1.cpp -o insertlist1
	#g++ insertlist2.cpp -o insertlist2
	./base
	./insert
	./quick
