all:
	gcc filestruct.c -o base
	g++ insertknuth.c -o insertknuth
	#gcc insertlist.c -o insertlist
	g++ quicksort.c  -o quick
	g++ merge.cpp -o merge
	g++ mergeknuth.cpp -o mergeknuth
	g++ mergeknuth1.cpp -o mergeknuth1

	#g++ insertlist1.cpp -o insertlist1
	#g++ insertlist2.cpp -o insertlist2
	./base
	./insertknuth
	./quick
	./merge
	./mergeknuth
	./mergeknuth1
